if (NOT DEFINED dk_utils_FOUND)
    set(DK_UTILS_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/src)
    set(DK_UTILS_LIBRARIES dk_utils CACHE INTERNAL "dk_utils library" FORCE)

    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args(dk_utils DEFAULT_MSG DK_UTILS_INCLUDE_DIRS DK_UTILS_LIBRARIES)
    mark_as_advanced(DK_UTILS_INCLUDE_DIRS DK_UTILS_LIBRARIES)
    set(DK_UTILS_FOUND 1)

    if (NOT TARGET dk_utils)
        if (DEFINED ENABLE_TESTS)
            set(tmp_ENABLE_TESTS ${ENABLE_TESTS})
        endif()
        set(ENABLE_TESTS 0)
        add_subdirectory(${CMAKE_CURRENT_LIST_DIR} ${CMAKE_CURRENT_BINARY_DIR}/dk_utils)
        unset(ENABLE_TESTS)
        if (DEFINED tmp_ENABLE_TESTS)
            set(ENABLE_TESTS ${tmp_ENABLE_TESTS})
            unset(tmp_ENABLE_TESTS)
        endif()
    endif()
endif()
