find_library(OPENGLES2_LIBRARY NAMES GLESv2)
set(OPENGLES2_LIBRARY_NEEDED OPENGLES2_LIBRARY)

# Include dir
find_path(OPENGLES2_INCLUDE_DIR NAMES gl2.h PATH_SUFFIXES GLES2)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args("OpenGLES2" DEFAULT_MSG
    ${OPENGLES2_LIBRARY_NEEDED}
    OPENGLES2_INCLUDE_DIR
)
